### ISSUE TITLE
sharing of the open rad project

### ISSUE THREAD

**Issue by aeonSolutions** [omarkhorshid/OpenRad#2]
Hi @omarkhorshid @M-run 
great project! 😍

i'm sharing it on my own "Safety & Health" project
https://github.com/aeonSolutions/AeonLabs-Safety-Health/wiki
👍

**Comment by omarkhorshid** [comment]
> Hi @omarkhorshid @M-run great project! 😍

Thank you so much, greatly appreciated!

> i'm sharing it on my own "Safety & Health" project https://github.com/aeonSolutions/AeonLabs-Safety-Health/wiki 👍

Looks like an informative and useful project, thanks for sharing.

**Comment by aeonSolutions** [comment]
Thank you.🙏 Very much appreciated.

I'm still doing a literature review while designing the open hardware electronics capable of detecting and monitoring 24\7 and sending collected sensor data to a repository where everyone can access and do statistical analysis, which includes official authorities and official law enforcement. 

Currently, the project already has available 2 Kicad projects for open hardware electronics capable of harvesting EM RF energy from the surrounding environment where it is installed. 

The devices have onboard technology for "sensor data validation" and this means collected sensor data can be used in cases of dispute and legal court.  More information here:
https://github.com/aeonSolutions/openScience-Smart-DAQ-to-Upload-Live-Experimental-Data-to-a-Data-Repository/wiki
