### ISSUE TITLE
Issue with WiFi SSID names

### ISSUE THREAD

**Issue by DarS007** [omarkhorshid/OpenRad#3]
Let me first thank You for the amazing piece of code! Great! I compiled it yesterday and successfully flashed to TTGO-Display. Pure joy.
However, today I faced an issue with proper settings for my WiFi. SSID of my WiFi has a **hyphen/dash** character in the middle (something like 'big-cow'). Your code properly displays it on the list of available networks, but when I select it (plus type the password) and try to save, I see the following error message:
_Please match the requested format.
Please enter only alphanumeric characters._
![20240913-fw_OpenRAD-bug-WiFi_SSID_name](https://github.com/user-attachments/assets/b0f97ee6-ce42-4537-963f-6624f1749b60)

Any chance to correct this misbehavior? Hyphens/dashes are legitimate characters for SSID names, so such error should not be generated.

Regards!
-DarS007

**Comment by M-run** [comment]
Hi @DarS007 

I’ve addressed the issue with the commit 09f67e0d99689ceec68074ea8dbd705513cdf6f6. Could you please test it and let me know if it resolves the problem on your end? Once we confirm that everything is working as expected, I’ll go ahead and close the issue.

Thanks for your help!

Best,
M-run

**Comment by DarS007** [comment]
Dear @M-run 
Thanks! Of course, the fix worked like a charm :-) Your change was in 'data' folder, so the Filesystem Image replacement sufficed to repair the bug. Go ahead and close the issue.
Once again, thank you for such marvelous code! Let me test it further.
Regards,
-DarS007

**Comment by M-run** [comment]
Dear @DarS007 
You're very welcome! I'm really glad the fix worked.
And thank you for your kind words.
Thanks again for the feedback, and I hope everything continues to run smoothly for you.

Best regards,
M-run
