### ISSUE TITLE
MQTT too chatty. Any chance to reduce the message frequency?

### ISSUE THREAD

**Issue by DarS007** [omarkhorshid/OpenRad#4]
I've configured & enabled MQTT and it works well. Even too well... It is very chatty. MQTT messages are being sent at least twice the second, whereas my desired frequency is just several per minute. Any chance to add/implement a new variable that can set/configure the frequency of MQTT messages? Or any suggestion which changes in code can slow it down?

I did a quick check and realized that _mqtt_task_ is pinned to core, but couldn't spot what triggers it (therefore how to reduce the frequency).

Regards,
-DarS007

**Comment by M-run** [comment]
Hi @DarS007 ,

Thanks for pointing that out! I've just committed a fix in 3b5bf4354f08943eaf07a1ae85f44d819777b82e that introduces a configurable mqtt_publish_interval variable. This will allow you to adjust the frequency of MQTT messages as needed.

By default, the interval is set to 0.5 seconds (500 milliseconds), but you can modify it to suit your requirements.

Feel free to pull the latest changes and let me know if this resolves the issue!

Best regards,
M-run

**Comment by DarS007** [comment]
Bingo! Your committed fix indeed did the trick. I set _mqtt_publish_interval_ to 25000 and now have the MQTT telemetry every 25 seconds. Enough for me and my home automation. 
One suggestion - for consistency, You can move this new variable to _settings.cpp_. But nevertheless, I'm happy with the current change and very thankful for the code & support!
Best regards,
-DarS007

**Comment by M-run** [comment]
Great! Glad to know that solved your issue.
Thank you for your suggestion by the way.

If you find any more issues or have any suggestions, do let us know.

Regards,
M-run
